export const biaozhun = [
	{
		types:[
			{title:'政治素养',score:8,id:1},
			{title:'业务能力',score:0,id:2},
			{title:'克难攻坚',score:0,id:3},
			{title:'带头上党课',score:15,id:4},
			{title:'通报批评',score:-8,id:5},
		]
	},
	{
		types:[
			{title:'理论学习',score:0,id:6},
			{title:'履职尽责',score:0,id:7},
			{title:'示范引领',score:0,id:8},
			{title:'发表文章',score:0,id:9},
			{title:'提醒谈话',score:-10,id:10},
		]
	},
	{
		types:[
			{title:'组织生活',score:0,id:11},
			{title:'创新创效',score:0,id:12},
			{title:'志愿者服务',score:0,id:13},
			{title:'荣誉表彰',score:0,id:14},
			{title:'其他扣分',score:-8,id:15},
		]
	},
	{
		types:[
			{title:'纪律作风',score:0,id:16},
			{title:'团结协作',score:0,id:17},
			{title:'服务群众',score:0,id:18},
			{title:'其他加分',score:0,id:19},
			{title:'',score:0,id:20},
		]
	},
	{
		types:[
			{title:'道德操守',score:0,id:21},
			{title:'遵章守纪',score:0,id:22},
			{title:'承诺践诺',score:0,id:23},
			{title:'',score:0,id:24},
			{title:'',score:0,id:25},
		]
	},
	{
		types:[
			{title:'意识形态',score:0,id:26},
			{title:'',score:0,id:27},
			{title:'',score:0,id:28},
			{title:'',score:0,id:29},
			{title:'',score:0,id:30},
		]
	},
	{
		types:[
			{title:'党费缴纳',score:0,id:31},
			{title:'',score:0,id:32},
			{title:'',score:0,id:33},
			{title:'',score:0,id:34},
			{title:'',score:0,id:35},
		]
	},
]